/-
Copyright (c) 2026 discovery-kernels contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.

R3 — minimal definitional layer for the operator-valued (OV) license.
STATEMENTS ONLY: the headline theorems of this tier are stated frontier and
remain `sorry` by design. Every definition here is a deliberately minimal
algebraic abstraction of an analytic object; docstrings name the informal
object and the citation, and flag simplifications.

References:
* T. Mai, R. Speicher, S. Yin — operator-valued semicircular elements /
  rationality of operator-valued resolvents and atomic support in amalgamated
  free probability (the "MSY-shaped" license).
* M. Fliess / M.-P. Schützenberger — recognizable (rational) noncommutative
  series and finite linear realizations, the algebraic backbone of
  "rational B-valued resolvent".

Human-review flag: per the project directive, R3 statements require operator
review before merge to main; see R3_OV/TIER-STATUS.md.
-/
import Mathlib

namespace DiscoveryKernels.R3

open Matrix

variable (B : Type*) [Ring B]

/-- The `k`-th shift of an operator-valued sequence `M : ℕ → B`. -/
def shiftOV (M : ℕ → B) (k : ℕ) : ℕ → B := fun n => M (n + k)

/-- The left `B`-submodule of `ℕ → B` generated by all shifts of `M`: the
operator-valued analogue of the Hankel row space. Informally this is the row
module of the `B`-valued Hankel matrix `(M (i+j))_{i,j}`; finite generation is
the operator-valued finite-Hankel-rank condition (cf. Mai–Speicher–Yin).
Simplification flag: we use the LEFT module structure; the amalgamated
(`B`-bimodule) structure of the analytic setting is not modelled here. -/
def ovHankelModule (M : ℕ → B) : Submodule B (ℕ → B) :=
  Submodule.span B (Set.range (shiftOV B M))

/-- Operator-valued finite Hankel rank: the module of shifts of `M` is a
finitely generated `B`-module. -/
def HasFiniteOVHankelRank (M : ℕ → B) : Prop :=
  Module.Finite B (ovHankelModule B M)

/-- `M` admits a finite linear realization over `B`: `M n = c ⬝ᵥ (Aⁿ *ᵥ b)` for
matrices/vectors over `B` of some finite size `N`. This is the algebraic form
of "the `B`-valued resolvent / moment generating series of `M` is rational"
(recognizable series in the sense of Schützenberger; in the free-probability
reading, a finite-dimensional realization of the `B`-valued Cauchy transform,
cf. Mai–Speicher–Yin). -/
def HasFiniteRealization (M : ℕ → B) : Prop :=
  ∃ (N : ℕ) (c : Fin N → B) (A : Matrix (Fin N) (Fin N) B) (b : Fin N → B),
    ∀ n : ℕ, M n = c ⬝ᵥ ((A ^ n) *ᵥ b)

/-- `M` is the moment sequence of a finitely atomic `B`-valued distribution:
finitely many atoms `a i` with `B`-valued weights `w i`, `M n = ∑ wᵢ aᵢⁿ`.
Simplification flag: in the analytic (MSY) setting the atoms live in the
spectrum of an operator affiliated to a von Neumann algebra with conditional
expectation `E_B`, and the weights are positive elements of `B`; here both are
abstracted to elements of `B`. -/
def IsFinitelyAtomicOV (M : ℕ → B) : Prop :=
  ∃ (k : ℕ) (w a : Fin k → B), ∀ n : ℕ, M n = ∑ i, w i * (a i) ^ n

end DiscoveryKernels.R3
